# /audit skill manifest
# 有边界的代码审计与修复 Skill
name: audit
version: 1.0.0
description: |
  有边界的代码审计与修复，避免无限深挖。
  分层标准：L1 阻塞性 / L2 功能性 / L3 最佳实践 / L4 过度优化。
  默认目标 L2，L1+L2 清零即宣布完成。
trigger: /audit
entry: SKILL.md
